# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_holder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bank_pb2 as bank__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='account_holder.proto',
  package='account_holder',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x61\x63\x63ount_holder.proto\x12\x0e\x61\x63\x63ount_holder\x1a\nbank.proto\"H\n\rAccountHolder\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x04\x62\x61nk\x18\x02 \x01(\x0b\x32\n.bank.Bank\x12\x0f\n\x07\x62\x61lance\x18\x03 \x01(\x03\x62\x06proto3')
  ,
  dependencies=[bank__pb2.DESCRIPTOR,])




_ACCOUNTHOLDER = _descriptor.Descriptor(
  name='AccountHolder',
  full_name='account_holder.AccountHolder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='account_holder.AccountHolder.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bank', full_name='account_holder.AccountHolder.bank', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='account_holder.AccountHolder.balance', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=124,
)

_ACCOUNTHOLDER.fields_by_name['bank'].message_type = bank__pb2._BANK
DESCRIPTOR.message_types_by_name['AccountHolder'] = _ACCOUNTHOLDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountHolder = _reflection.GeneratedProtocolMessageType('AccountHolder', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTHOLDER,
  __module__ = 'account_holder_pb2'
  # @@protoc_insertion_point(class_scope:account_holder.AccountHolder)
  ))
_sym_db.RegisterMessage(AccountHolder)


# @@protoc_insertion_point(module_scope)
