# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: all_accounts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import account_holder_pb2 as account__holder__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='all_accounts.proto',
  package='all_accounts',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x61ll_accounts.proto\x12\x0c\x61ll_accounts\x1a\x14\x61\x63\x63ount_holder.proto\"{\n\x0c\x61ll_accounts\x12\x34\n\rAccountHolder\x18\x01 \x01(\x0b\x32\x1d.account_holder.AccountHolder\x12\x35\n\x0e\x41\x63\x63ountHolders\x18\x02 \x03(\x0b\x32\x1d.account_holder.AccountHolderb\x06proto3')
  ,
  dependencies=[account__holder__pb2.DESCRIPTOR,])




_ALL_ACCOUNTS = _descriptor.Descriptor(
  name='all_accounts',
  full_name='all_accounts.all_accounts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccountHolder', full_name='all_accounts.all_accounts.AccountHolder', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AccountHolders', full_name='all_accounts.all_accounts.AccountHolders', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=181,
)

_ALL_ACCOUNTS.fields_by_name['AccountHolder'].message_type = account__holder__pb2._ACCOUNTHOLDER
_ALL_ACCOUNTS.fields_by_name['AccountHolders'].message_type = account__holder__pb2._ACCOUNTHOLDER
DESCRIPTOR.message_types_by_name['all_accounts'] = _ALL_ACCOUNTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

all_accounts = _reflection.GeneratedProtocolMessageType('all_accounts', (_message.Message,), dict(
  DESCRIPTOR = _ALL_ACCOUNTS,
  __module__ = 'all_accounts_pb2'
  # @@protoc_insertion_point(class_scope:all_accounts.all_accounts)
  ))
_sym_db.RegisterMessage(all_accounts)


# @@protoc_insertion_point(module_scope)
