# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='bank',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nbank.proto\x12\x04\x62\x61nk\",\n\x04\x42\x61nk\x12\x11\n\tbank_name\x18\x01 \x01(\t\x12\x11\n\tbank_code\x18\x02 \x01(\x05\x62\x06proto3')
)




_BANK = _descriptor.Descriptor(
  name='Bank',
  full_name='bank.Bank',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bank_name', full_name='bank.Bank.bank_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bank_code', full_name='bank.Bank.bank_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['Bank'] = _BANK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bank = _reflection.GeneratedProtocolMessageType('Bank', (_message.Message,), dict(
  DESCRIPTOR = _BANK,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:bank.Bank)
  ))
_sym_db.RegisterMessage(Bank)


# @@protoc_insertion_point(module_scope)
